AXADev.Exams/Models/RequestAPI.cs
using System.Collections.Generic;

namespace AXADev.Exams.Models {
    public class RequestAPI {
        public RequestAPI() {
            Headers = new List<RequestAPIHeader>();
        }

        public string Uri { get; set; }
        public string Method { get; set; }
        public string ContentType { get; set; }
        public List<RequestAPIHeader> Headers { get; set; }
        public object Body { get; set; }
    }
}

AXADev.Exams/Models/RequestAPIHeader.cs
namespace AXADev.Exams.Models {
    public class RequestAPIHeader {
        public string Property { get; set; }
        public string Value { get; set; }
    }
}

AXADev.Exams/Controllers/Demo1Controller.cs
using AXADev.Exams.Helpers;
using AXADev.Exams.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Web.Mvc;


namespace AXADev.Exams.Controllers {
    public class Demo1Controller : Controller {
        // GET: Demo1
        public ActionResult Index() {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitResult(FormCollection form) {

            var request = new RequestAPI {
                Uri = "https://goodmorning-axa-dev.azure-api.net/register",
                Method = "POST",
                ContentType = "application/json",
                Body = new {
                    Name = Convert.ToString(form["name"]),
                    Email = Convert.ToString(form["email"]),
                    Mobile = Convert.ToString(form["mobile"]),
                    PositionApplied = Convert.ToString(form["position"])
                }
            };

            var result = JObject.FromObject(RequestAPIHelper.Send(request));

            return View(result);
        }

    }
}

AXADev.Exams/Controllers/Demo2Controller.cs
using AXADev.Exams.Helpers;
using AXADev.Exams.Models;
using Newtonsoft.Json.Linq;
using System.Web;
using System.Web.Mvc;


namespace AXADev.Exams.Controllers {
    public class Demo2Controller : Controller {
        // GET: Demo2
        public ActionResult Index() {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitResult(HttpPostedFileBase file) {

            var request = new RequestAPI {
                Uri = "https://goodmorning-axa-dev.azure-api.net/upload",
                Method = "POST",
                ContentType = "application/json",
                Body = new {
                    file = new {
                        mime = "application/pdf",
                        data = StringHelper.FileToBase64String(file)
                    }
                }
            };

            request.Headers.Add(new RequestAPIHeader() {
                Property = "x-axa-api-key",
                Value = "2838c637-5424-4889-b09d-af3cc149c0fe"
            });

            var result = JObject.FromObject(RequestAPIHelper.Send(request));

            return View(result);
        }

    }
}

AXADev.Exams/Controllers/Demo3Controller.cs
using AXADev.Exams.Helpers;
using AXADev.Exams.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Web;
using System.Web.Mvc;


namespace AXADev.Exams.Controllers {
    public class Demo3Controller : Controller {
        // GET: Demo3
        public ActionResult Index() {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitResult(FormCollection form) {

            var request = new RequestAPI {
                Uri = "https://goodmorning-axa-dev.azure-api.net/schedule",
                Method = "POST",
                ContentType = "application/json",
                Body = new {
                    ProposedDate = Convert.ToString(form["date"]),
                    ProposedTime = Convert.ToString(form["time"]),
                    Online = "true"
                }
            };

            request.Headers.Add(new RequestAPIHeader() {
                Property = "x-axa-api-key",
                //Value = "4bd85c83-28a9-4681-af5e-297b19bbabac"
                Value = "2838c637-5424-4889-b09d-af3cc149c0fe"
            });

            var result = JObject.FromObject(RequestAPIHelper.Send(request));

            return View(result);
        }

    }
}

AXADev.Exams/Controllers/HomeController.cs
using System.Web.Mvc;

namespace AXADev.Exams.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }

    }
}

AXADev.Exams/Views/Demo1/Index.cshtml
@{
    ViewBag.Title = "Demo 1";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8 pb-5">

            <form action="@Url.Action("SubmitResult","Demo1")" method="post">
                <div class="card border-axa-blue rounded-0">
                    <div class="card-header p-0">
                        <div class="border-primary text-axa-blue text-center py-2">
                            <h3><i class="fa fa-envelope"></i> Application Form</h3>
                        </div>
                    </div>
                    <div class="card-body p-3">

                        <!--Body-->
                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-user text-axa-blue"></i></div>
                                </div>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Full Name" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-envelope text-axa-blue"></i></div>
                                </div>
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email Address" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-phone text-axa-blue"></i></div>
                                </div>
                                <input type="text" class="form-control" id="mobile" name="mobile" placeholder="Mobile Number (09xxxxxxxxxx)" required pattern="09[0-9]{9}">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-suitcase text-axa-blue"></i></div>
                                </div>
                                <input type="text" class="form-control" id="position" name="position" placeholder="Position Applied" required>
                            </div>
                        </div>

                        <div class="text-center">
                            <input type="submit" value="Submit" class="btn btn-primary bg-axa-blue btn-block rounded-0 py-2">
                        </div>
                    </div>

                </div>
            </form>

        </div>
    </div>
</div>

AXADev.Exams/Views/Demo1/SubmitResult.cshtml
@model  Newtonsoft.Json.Linq.JObject

<div class="jumbotron text-center">
    @if (Model["errorMessage"] != null) {
        <h1 class="display-3 text-danger">Sorry :(</h1>
        <p class="lead">@Model["errorMessage"]</p>
    } else {
        <h1 class="display-3 text-success">Thank you!</h1>
        <p class="lead">@Model["Message"]</p>
    }
    <p class="lead">
        <a class="btn btn-primary btn-sm" href="@Url.Action("Index","Home")" role="button">Return to Homepage</a>
    </p>
</div>

AXADev.Exams/Views/Demo2/Index.cshtml
@{
    ViewBag.Title = "Demo 2";
}

@section scripts{
    @Scripts.Render("~/Scripts/www/Demo2.js")
}


<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-11 col-lg-10 pb-5">
            

            <form action="@Url.Action("SubmitResult","Demo2")" id="frmResumeSend" method="post" enctype="multipart/form-data">
                <div class="card border-axa-blue rounded-0">
                    <div class="card-header p-0">
                        <div class="border-primary text-axa-blue text-center py-2">
                            <h3><i class="fa fa-file-pdf-o"></i> Send your Resume</h3>
                        </div>
                    </div>
                    <div class="card-body p-3">

                        <div class="container">
                            <h4>Please upload your resume:</h4>
                            <div class="custom-file mb-5">
                                <input type="file" class="custom-file-input" accept=".pdf" id="file" name="file">
                                <label class="custom-file-label" for="fileUpload">Choose file</label>
                            </div>
                        </div>

                        <div class="text-center mt-3">
                            <input type="submit" value="Submit" class="btn btn-primary bg-axa-blue btn-block rounded-0 py-2">
                        </div>
                    </div>

                </div>
            </form>

        </div>
    </div>
</div>

AXADev.Exams/Views/Demo2/SubmitResult.cshtml
@model  Newtonsoft.Json.Linq.JObject

<div class="jumbotron text-center">
    @if (Model["errorMessage"] != null) {
        <h1 class="display-3 text-danger">Sorry :(</h1>
        <p class="lead">@Model["errorMessage"]</p>
    } else {
        <h1 class="display-3 text-success">Thank you!</h1>
        <p class="lead">@Model["Message"]</p>
    }
    <p class="lead">
        <a class="btn btn-primary btn-sm" href="@Url.Action("Index","Home")" role="button">Return to Homepage</a>
    </p>
</div>

AXADev.Exams/Views/Demo3/Index.cshtml
@{
    ViewBag.Title = "Demo 1";
}

@section scripts{
    @Scripts.Render("~/Scripts/www/Demo3.js")
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-11 col-lg-10 pb-5">

            <form action="@Url.Action("SubmitResult","Demo3")" method="post">
                <div class="card border-axa-blue rounded-0">
                    <div class="card-header p-0">
                        <div class="border-primary text-axa-blue text-center py-2">
                            <h3><i class="fa fa-handshake-o"></i> Schedule an Interview</h3>
                        </div>
                    </div>
                    <div class="card-body p-3">

                        <div class="container">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="input-group date" id="date" data-target-input="nearest">
                                            <input type="text" name="date" class="form-control datetimepicker-input" data-target="#date" placeholder="Proposed Date" />
                                            <div class="input-group-append" data-target="#date" data-toggle="datetimepicker">
                                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="input-group date" id="time" data-target-input="nearest">
                                            <input type="text" name="time" class="form-control datetimepicker-input" data-target="#time" placeholder="Proposed Time" />
                                            <div class="input-group-append" data-target="#time" data-toggle="datetimepicker">
                                                <div class="input-group-text"><i class="fa fa-clock-o"></i></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <i>Pro-tip: Usually available in the afternoon. Wednesdays or Thursdays are generally relaxed. So pick one and get a slot.</i>
                        </div>


                        <div class="text-center mt-4">
                            <input type="submit" value="Submit" class="btn btn-primary bg-axa-blue btn-block rounded-0 py-2">
                        </div>
                    </div>

                </div>
            </form>

        </div>
    </div>
</div>

AXADev.Exams/Views/Demo3/SubmitResult.cshtml
@model  Newtonsoft.Json.Linq.JObject

<div class="jumbotron text-center">
    @if (Model["errorMessage"] != null) {
        <h1 class="display-3 text-danger">Sorry :(</h1>
        <p class="lead">@Model["errorMessage"]</p>
    } else {
        <h1 class="display-3 text-success">Thank you!</h1>
        <p class="lead">@Model["Message"]</p>
    }
    <p class="lead">
        <a class="btn btn-primary btn-sm" href="@Url.Action("Index","Home")" role="button">Return to Homepage</a>
    </p>
</div>

AXADev.Exams/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="row">
    <div class="col-12 col-md-4">
        <h2>Demo 1</h2>
        <p><a class="btn btn-default" href="@Url.Action("Index","Demo1")">Check &raquo;</a></p>
    </div>
    <div class="col-12 col-md-4">
        <h2>Demo 2</h2>
        <p><a class="btn btn-default" href="@Url.Action("Index","Demo2")">Check &raquo;</a></p>
    </div>
    <div class="col-12 col-md-4">
        <h2>Demo 3</h2>
        <p><a class="btn btn-default" href="@Url.Action("Index","Demo3")">Check &raquo;</a></p>
    </div>
</div>

AXADev.Exams/Views/Shared/Partials/_Footer.cshtml
<div class="container-fluid">
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - AXA DEV Exam Application</p>
    </footer>
</div>

AXADev.Exams/Views/Shared/Partials/_Header.cshtml
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">AXA Dev Exams</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Home")">
                    <i class="fa fa-home"></i>
                    Home
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Exams
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="@Url.Action("Index","Demo1")">Demo 1</a>
                    <a class="dropdown-item" href="@Url.Action("Index","Demo2")">Demo 2</a>
                    <a class="dropdown-item" href="@Url.Action("Index","Demo3")">Demo 3</a>
                </div>
            </li>
        </ul>
        
    </div>
</nav>

AXADev.Exams/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("Partials/_Header")
    <div class="container body-content">
        @RenderBody()
    </div>
    @Html.Partial("Partials/_Footer")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>